import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import LiveBlocksProvider from "@/components/LiveBlocksProvider";
import { ThemeProvider } from "@/components/ThemeProvider";
import LocaleProvider from "@/components/LocaleProvider";
import LayoutWrapper from "@/components/LayoutWrapper";
import { ZenModeProvider } from "@/contexts/ZenModeContext";
import { cookies } from "next/headers";
import { defaultLocale, getDictionary, isLocale, type Locale } from "@/lib/i18n";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const localeCookie = cookieStore.get("locale")?.value;
  const locale: Locale = isLocale(localeCookie) ? localeCookie : defaultLocale;
  const dictionary = await getDictionary(locale);

  return (
    <ClerkProvider>
      <LiveBlocksProvider>
        <html lang={locale} suppressHydrationWarning>
          <body suppressHydrationWarning>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem={true}
              storageKey="editor-theme"
            >
              <LocaleProvider locale={locale} dictionary={dictionary}>
                <ZenModeProvider>
                  <LayoutWrapper>
                    {children}
                  </LayoutWrapper>
                  <Toaster position="top-center" />
                </ZenModeProvider>
              </LocaleProvider>
            </ThemeProvider>
          </body>
        </html>
      </LiveBlocksProvider>
    </ClerkProvider>
  );
}
