import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "sonner";
import LiveBlocksProvider from "@/components/LiveBlocksProvider";
import Chatbar from "@/components/Chatbar";
import { ThemeProvider } from "@/components/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <LiveBlocksProvider>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <html lang="en">
            <body>
              <Header />
              <div className="flex min-h-screen">
                <Sidebar />
                <div className="flex-1 bg-gray-100 dark:bg-gray-900 overflow-y-auto scrollbar-hide">
                  {children}
                </div>
              </div>
              <Chatbar />
              <Toaster position="top-center" />
            </body>
          </html>
        </ThemeProvider>
      </LiveBlocksProvider>
    </ClerkProvider>
  );
}
