import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "sonner";
import LiveBlocksProvider from "@/components/LiveBlocksProvider";
import Chatbar from "@/components/Chatbar";
import { ThemeProvider } from "@/components/ThemeProvider";
import LocaleProvider from "@/components/LocaleProvider";
import { cookies } from "next/headers";
import { defaultLocale, getDictionary, isLocale, type Locale } from "@/lib/i18n";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const localeCookie = cookieStore.get("locale")?.value;
  const locale: Locale = isLocale(localeCookie) ? localeCookie : defaultLocale;
  const dictionary = await getDictionary(locale);

  return (
    <ClerkProvider>
      <LiveBlocksProvider>
        <html lang={locale} suppressHydrationWarning>
          <body suppressHydrationWarning>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem={true}
              storageKey="editor-theme"
            >
              <LocaleProvider locale={locale} dictionary={dictionary}>
                <Header />
                <div className="flex min-h-screen">
                  <Sidebar />
                  <div className="flex-1 bg-gray-100 dark:bg-gray-900 overflow-y-auto scrollbar-hide">
                    {children}
                  </div>
                </div>
                <Chatbar />
                <Toaster position="top-center" />
              </LocaleProvider>
            </ThemeProvider>
          </body>
        </html>
      </LiveBlocksProvider>
    </ClerkProvider>
  );
}
